### ISSUE TITLE
Fragen für Qualitative Studie

### ISSUE THREAD

**Issue by darenegade** [peter-mueller/knocklock#7]
Es sollten 3-4 Fragen zur Akzeptanz und Funktion des KnockLocks auf die Webseite integriert werden. Dieses sollten unter der USER-UID in Firebase gespeichert werden

**Comment by darenegade** [comment]
### Mögliche Fragen

**1 (sehr gut/wenig/stark) - 5 (schlecht/viele/schwach)**
- [ ] Wie findest du die Eingabe? 
- [ ] Wie bewertest du die Sicherheit des KnockLocks?
- [ ] Gab es Probleme beim Speichern des Musters?
- [ ] Gab es Probleme beim Entsperren?
- [ ] Würdest du den KnockLock gegenüber einem Passwort bevorzugen?

**Comment by darenegade** [comment]
@peter-mueller Was meinst du?

**Comment by darenegade** [comment]
Fragen sind integriert. Es fehlt nur noch Feedback Peter 😄

**Comment by peter-mueller** [comment]
Wie bist du auf dein Kopfzeichen gekommen?

**Comment by darenegade** [comment]
Gute Frage, aber willst du wirklich Freitext Fragen mit reinnehmen?

**Comment by peter-mueller** [comment]
Nur die eine optional am Ende, wenn man sieht dass nichts mehr kommt

**Comment by darenegade** [comment]
okay, willst du die noch einbauen?
Sonst passen die anderen Fragen?

**Comment by darenegade** [comment]
Ich hab die Textfrage noch eingebaut. Wir müssen morgen die Studie veröffentlichen, da es sonst zeitlich SEHR eng wird (Am Sonntag ist die Abgabe vom Poster)
