### ISSUE TITLE
Ripple entfernen

### ISSUE THREAD

**Issue by peter-mueller** [peter-mueller/knocklock#9]
Der ripple verwirrt mich total bei der Eingabe.

Ist es okay wenn ich das nach https://codepen.io/anon/pen/goyEva ändere?

**Comment by darenegade** [comment]
Die Alternative finde ich persönlich nicht so schön und etwas zu schwach im Eingabe-Feedback.
Ich habe Marlies beides probieren lassen und gefragt, was sie besser findet. Sie war auch für ripple. 
Was stört dich den genau an dem ripple?
Reicht es vielleicht, wenn man den nur etwas anpasst?
Oder du machst eine 3. Alternative, wie in deinem CodePen Vorschlage nur mit einem stärkeren Effekt oder so

**Comment by darenegade** [comment]
Oder du baust noch eine key-binding beim paper-button auf die Leertaste oder so ein

**Comment by peter-mueller** [comment]
ok dann lassen wirs so
